ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorfusion
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/rear_als/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/rear_als/rear_alshub
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/rear_flicker/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/rear_flicker/rear_flickerhub
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/oplus_virtual_sensor

obj-$(CONFIG_MTK_SENSOR_SUPPORT) += sensor_probe.o
